# https://taskfile.dev

version: '3'
dotenv: ['.env']
output: prefixed
silent: true

env:

vars:
  TODAY: '{{ now | date "2006-01-02T15:04:05-07:00" }}'
  black: \033[:0;30m
  red: \033[:0;31m
  green: \033[:0;32m
  orange: \033[:0;33m
  blue: \033[:0;34m
  purple: \033[:0;35m
  cyan: \033[:0;36m
  light_gray: \033[:0;37m
  dark_gray: \033[:1;30m
  light_red: \033[:1;31m
  light_green: \033[:1;32m
  yellow: \033[:1;33m
  light_blue: \033[:1;34m
  light_purple: \033[:1;35m
  light_cyan: \033[:1;36m
  white: \033[:1;37m
  nocolor: \u001b[0m
  reversed: \u001b[7m

# includes:
#   aws: ./aws
#   docker: ./docker
#   terraform: ./terraform

tasks:
  default:
    desc: Root Taskfile
    prefix: ⚙️ 
    cmds:
      - task -l

  example1:
    prefix: ⚙️ > example1
    cmds:
      - echo -e "{{.light_cyan}} 🔥 {{ .reversed }} To-Do  {{.nocolor}}"
      - echo -e "{{.green}} ✅ Command succeeded, validated homebrew installed {{.nocolor}}"
      - echo -e "{{.red}} ❗ Command failed. Homebrew not detected {{.nocolor}}"
      - echo -e "{{.light_gray}} ℹ {{ .reversed }} Info {{ .nocolor }}"
        