# https://taskfile.dev

version: '3'
dotenv: ['.env']
output: prefixed
vars:
env:

includes:
  aws: ./aws
  docker: ./docker
  terraform: ./terraform

tasks:

  default:
    desc: Hello MSG.
    cmds:
      - echo "{{.GREETING}}"
    silent: true
